services:
  - type: web
    name: nodejs-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
  - type: web
    name: mongo
    runtime: docker
    envVars:
      - key: PORT
        value: 27017
    image:
      url: library/mongo:latest
